name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: younglinkregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker build -t younglinkregistry.azurecr.io/myapp:${{ github.sha }} -f Dockerfile.3 .

    - name: Push Docker image to Azure Container Registry
      run: docker push younglinkregistry.azurecr.io/myapp:${{ github.sha }}
